//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Cake.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Reflection;
using System.Runtime.InteropServices;

[assembly: AssemblyTitle("Cake.Jira.Tests")]
[assembly: AssemblyDescription("")]
[assembly: AssemblyCompany("Hugo Tavares")]
[assembly: AssemblyProduct("Cake.Jira.Tests")]
[assembly: AssemblyCopyright("Copyright © Hugo Tavares 2018")]
[assembly: AssemblyTrademark("")]
[assembly: Guid("36591b01-1d3b-4dc0-b3e0-c57ee3ee995b")]
[assembly: ComVisible(false)]

